### PR TITLE
Smash Magazine Heat Map

### PR DESCRIPTION
**Pull request by tGodson**
a heat map of the smash magazine. This heat map contains 3 shades of grey and the darkest shade of gey is the part which will pull the most attention to the user at a glance.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @tGodson and @haraphat01, your project looks super cool 👍 Great use of HTML semantics 😄 
Let us address the comments below:

- Let us implement the float technique, at least 2 or more elements with the float technique will be great
f1
- The footer contains center links, currently, we do not have centered links
f
- Let us implement the DRY rule, so we avoid repeating code. This [article](https://speckyboy.com/good-bad-css-practices/) will help
Going forward, this [article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) will help us write great commit messages


Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack for more information

**Comment by tGodson** [comment]
Done all the corrections recommended by the TSE

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright) Consider no repeating the same rule as the last TSE required, here is an example:

Screenshot from 2020-04-17 18-14-19

- [x] As the last TSE required: The footer contains centered links (content is not important) ([link](https://www.smashingmagazine.com/) to page)




- [x] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)) Consider use the Microverse 'Linters'. 

[OPTIONAL]

- [x] Consider adding the 'demo link' working ;)

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by tGodson** [comment]
Made all the corrections required the TSE

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @haraphat01  & @tGodson  :wave:
-
You have done a splendid job implementing some of the changes! :tada: keep it up.
We, however, do have some pending changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - REMOVE - This space
- This latest post section has some spacing in it that is not necessary, lets, remove it.

| [Your Page](https://raw.githack.com/tGodson/Smah-Magazine-Heat-Map/feature/index.html) | [Source Page](https://www.smashingmagazine.com/) |
|:-----:|:-----:|
|latest-post-clone|latest-post|

## [REQUIRED] - FIX - The footer section
- The contents at the footer section have not been properly centred, we should aim to have it mimic the source page.

| [Your Page](https://raw.githack.com/tGodson/Smah-Magazine-Heat-Map/feature/index.html) | [Source Page](https://www.smashingmagazine.com/) |
|:-----:|:-----:|
| links-clone | links |


## [REQUIRED] - IMPLEMENT - The DRY principle
- Just as @addod19 pointed out, we still have some repeating code inside of your stylesheets. AN example is as shown below: 👇 
repeated-code
- We can merge these classes and style them together. 

## [OPTIONAL] - INCREASE - The heights of the sections
- Most of your sections' height is not  the same as with the source example 👇 

| [Your Page](https://raw.githack.com/tGodson/Smah-Magazine-Heat-Map/feature/index.html) | [Source Page](https://www.smashingmagazine.com/) |
|:-----:|:-----:|
|2-contents-clone|2-contents|

Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by MarioDena** [comment]
## Project approved 

Good work team go ahead and merge.

Cheers!

**Pull request merged**
